@startuml
hide footbox
agent "Care Services Selective Supplier" as SelectiveSupplier
agent "Care Services Selective Consumer" as SelectiveConsumer
agent "Care Services Update Supplier" as UpdateSupplier
agent "Care Services Update Consumer" as UpdateConsumer
SelectiveConsumer -> SelectiveSupplier : "Find Matching Care Services [ITI-90]"
SelectiveConsumer -[hidden]-> UpdateConsumer
UpdateConsumer -> UpdateSupplier : "Request Care Services Updates [ITI-91]"
@enduml