@startuml
hide footbox

frame QueryClient {
agent "Care Services Selective Consumer" as Query
}

frame UpdateClient {
  agent "Care Services Update Consumer" as Consumer
}

frame Directory {
agent "Care Services Selective Supplier" as Selective
agent "Care Services Update Supplier" as Supplier
}

Query --> Selective: Find Matching Care Services\n[ITI-90]
Consumer --> Supplier: Request Care Services Updates\n[ITI-91]

@enduml