@startuml basic-deployment
hide footbox
skinparam linetype polyline


agent "Query Client" as Query
agent "Update Client" as Update
agent "Directory" as Directory

Query --> Directory: Find Matching Care Services\n[ITI-90]
Update --> Directory: Request Care Services Updates\n[ITI-91]

@enduml