@startuml
hide footbox

title Organization-specific Endpoints Hosted by Parent, Affiliation or Hidden Intermediary

object "Organization A" as OrganizationA
object "Parent Organization B" as OrganizationB
object "Endpoint for A" as EndpointA
EndpointA : address = https://orgB.org/orgA

OrganizationA --> OrganizationB : partOf
OrganizationA --> EndpointA : endpoint
OrganizationB ..> EndpointA : hosts

object "Organization C" as OrganizationC
object "Affiliated Organization D" as OrganizationD
object "OrganizationAffiliation" as OrgAff
object "Endpoint for C" as EndpointC
EndpointC : address = https://orgD.org/orgC

OrgAff --> OrganizationC : participatingOrganization
OrgAff --> OrganizationD : organization
OrganizationC --> EndpointC : endpoint
OrganizationD ..> EndpointC : hosts

object "Organization E" as OrganizationE
object "Endpoint for E" as EndpointE
EndpointE : address = https://intermediaryF.org/orgE

OrganizationE --> EndpointE : endpoint
note "Intermediary F\nnot listed in directory." as N1
N1 .. EndpointE

@enduml
