@startuml
hide footbox

object "Organization A" as OrganizationA
object "Organization B" as OrganizationB
object "Endpoint" as EndpointA
object "Organization C" as OrganizationC
object "Organization D" as OrganizationD
object "Organization E" as OrganizationE
object ":OrganizationAffiliation" as OrgAff
OrgAff : code = DocShare-federate
OrgAff -> OrganizationB : participatingOrganization
OrganizationA <-- OrgAff : organization

EndpointA <- OrganizationA : endpoint
OrganizationB <-- OrganizationC : partOf
OrganizationB <-- OrganizationD : partOf
OrganizationB <-- OrganizationE : partOf

@enduml
