@startuml
hide footbox

title Organization-specific Endpoint Hosted by Hidden Intermediary

object "Organization E" as OrganizationE
object "Endpoint for E" as EndpointE
EndpointE : address = https://intermediaryF.org/orgE

OrganizationE -> EndpointE : endpoint
note "Intermediary F\nnot listed in directory." as N1
N1 .. EndpointE

@enduml
