@startuml
hide footbox

object "Organization C" as OrganizationC
object "Affiliated Organization D" as OrganizationD
object "OrganizationAffiliation" as OrgAff
object "Endpoint for C" as EndpointC
EndpointC : address = https://orgD.org/orgC

OrgAff --> OrganizationC : participatingOrganization
OrganizationD <-- OrgAff : organization
OrganizationC -> EndpointC : endpoint
OrganizationD ..> EndpointC : hosts

@enduml
