@startuml dir-endpoint-to-org-affiliates
hide footbox

object "Organization A" as OrganizationA
object "Organization B" as OrganizationB
object "Endpoint" as EndpointA
object "Organization C" as OrganizationC
object "OrganizationAffiliation" as OrgAff
OrgAff : code = DocShareFederateExt
OrgAff --> OrganizationB : participatingOrganization
OrganizationA <-- OrgAff : organization
object "OrganizationAffiliation" as OrgAff2
OrgAff2 : code = DocShareFederateExt
OrgAff2 --> OrganizationC : participatingOrganization
OrganizationA <-- OrgAff2 : organization

EndpointA <-- OrganizationA : endpoint
EndpointA <- OrgAff : endpoint
EndpointA <- OrgAff2 : endpoint

@enduml
