@startuml ITI-91-seq
hide footbox
participant "Update Client" as Client
participant "Directory" as Server
activate Client
activate Server
Client -> Server : 1. Request Care Services Updates Request [ITI-91]
Server --> Client : 2. Request Care Services Updates Response [ITI-91]
deactivate Client
deactivate Server
@enduml