@startuml ITI-130-seq
hide footbox
participant "Data Source" as Client
participant "Directory" as Server
activate Client
activate Server
==Create Care Services Resource Message==
Client -> Server : Create Care Services Resource Request [ITI-130]
Server --> Client : Create Care Services Resource Response [ITI-130]
==Update Care Services Resource Message==
Client -> Server : Update Care Services Resource Request [ITI-130]
Server --> Client : Update Care Services Resource Response [ITI-130]
==Delete Care Services Resource Message==
Client -> Server : Delete Care Services Resource Request [ITI-130]
Server --> Client : Delete Care Services Resource Response [ITI-130]
==Process Care Services Resources Message==
Client -> Server : Process Care Services Resources Request [ITI-130]
Server --> Client : Process Care Services Resources Response [ITI-130]
deactivate Client
deactivate Server
@enduml