@startuml
hide footbox

frame Client {
agent "Care Services Update Consumer" as Consumer
}

frame Server {
agent "Care Services Update Supplier" as Supplier
}

Consumer -> Supplier: Find Matching Care Services\n[ITI-90]

@enduml