@startuml
hide footbox

participant "MFL\nCare Services Update Supplier" as MFL
participant "HRIS\nCare Services Update Consumer" as HRIS
participant "LMIS\nCare Services Update Consumer" as LMIS

activate HRIS
activate MFL
HRIS -> MFL: Request Care Services Updates [ITI-91] request
MFL -> HRIS: Request Care Services Updates [ITI-91] response
deactivate HRIS

activate LMIS
LMIS -> MFL: Request Care Services Updates [ITI-91] request
MFL -> LMIS: Request Care Services Updates [ITI-91] response
deactivate MFL
deactivate LMIS

@enduml