@startuml usecase3-diagram
hide footbox

title Cross-Jurisdictional Data Exchange

agent "Operating Unit\nUpdate Client" as OU
agent "Ministry of Health\nDirectory" as MOH
collections "Implementing Partner\nDirectory" as Partner

OU --> MOH
OU --> Partner

@enduml