@startuml usecase2-processflow
hide footbox
participant "Health Worker" as HW
participant "Emergency Responder\Query Client" as ER
participant "National HIE\nUpdate Client\nDirectory" as NHIE
participant "State HIE\nDirectory" as SHIE

loop Regular update of practitioner information
activate NHIE
activate SHIE
NHIE -> SHIE : Request Care Services Updates request [ITI-91]
SHIE -> NHIE : Request Care Services Updates response [ITI-91]\nFHIR Bundle of Updated resources
deactivate NHIE
deactivate SHIE
end

activate HW
activate ER
HW -> ER : Reports for volunteer duty

activate NHIE
ER -> NHIE : Find Matching Care Services request [ITI-90]
NHIE -> ER : Find Matching Care Services response [ITI-90]\nFHIR Bundle of matching resources
deactivate NHIE

ER -> HW : Allow or deny access
deactivate HW
deactivate ER

@enduml