@startuml
hide footbox

title Federated Endpoints via Parent or Affiliation

object "Organization A" as OrganizationA
OrganizationA : identifier = 1.2.3
object "Parent Organization B" as OrganizationB
object "Endpoint for B" as EndpointB
EndpointB : address = https://orgB.org

OrganizationA --> OrganizationB : partOf
OrganizationB --> EndpointB : endpoint

object "Organization C" as OrganizationC
OrganizationC : identifier = 4.5.6
object "Affiliated Organization D" as OrganizationD
object "OrganizationAffiliation" as OrgAff
OrgAff : code = DocShare-federate
object "Endpoint for D" as EndpointD
EndpointD : address = https://orgD.org

OrgAff --> OrganizationC : participatingOrganization
OrgAff --> OrganizationD : organization
OrganizationD --> EndpointD : endpoint

@enduml
