@startuml
hide footbox

participant "MFL\nDirectory" as MFL
participant "HRIS\nUpdate Client" as HRIS
participant "LMIS\nUpdate Client" as LMIS

activate HRIS
activate MFL
HRIS -> MFL: Request Care Services Updates [ITI-91] request
MFL -> HRIS: Request Care Services Updates [ITI-91] response
deactivate HRIS

activate LMIS
LMIS -> MFL: Request Care Services Updates [ITI-91] request
MFL -> LMIS: Request Care Services Updates [ITI-91] response
deactivate MFL
deactivate LMIS

@enduml